---
- hosts : localhost
  connection : local
  become : true 
  vars : 
   env : "{{env}}"
   ansible_python_interpreter: /usr/bin/python3
  tasks : 
  - name : Installing Java 8 
    apt :
             name : openjdk-8-jdk 
             state : present 
             update_cache : yes
  - name: add tomcat group
    group:
     name: tomcat

  - name: add tomcat user
    user:
             name: tomcat
             group: tomcat
             #home: /user/share/tomcat
             #createhome: no

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download tomcat 9
    get_url:
            url : https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz
            dest: /opt/tomcat

  - name: extract tomcat packages
    unarchive:
      src: /opt/tomcat/apache-tomcat-9.0.56.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]
  - name: Change ownership
    file:
     path: /opt/tomcat
     owner: tomcat
     group: tomcat
     mode: "u+rwx,g+rx,o=rx"
     recurse: yes
     state: directory
  - name: Deploying sample.war on tomcat Server
    ansible.builtin.copy :
             src : /data/sample.war
             dest : /opt/tomcat/webapps
  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat9.service
       dest: /etc/systemd/system/
       mode: 0755
  - name: testing if environement (Dev )
    lineinfile : 
     path : /etc/systemd/system/tomcat9.service
     search_string : '-Xmx1024M'
     line : Environment='CATALINA_OPTS=-Xms128M -Xmx256M -server -XX:+UseParallelGC'
    when : env == 'DEV'

  - name: testing if environement is Prod
    lineinfile : 
       path : /etc/systemd/system/tomcat9.service
       search_string : '-Xmx1024M'
       line : Environment='CATALINA_OPTS=-Xms256M -Xmx512M -server -XX:+UseParallelGC'
    when : env == 'PROD'

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat9
      state: started
      enabled: true
      daemon_reload: true

      #  - name: start tomcat services
      #shell: nohup /usr/local/apache-tomcat-9.0.44/bin/startup.sh

